import React, { useState } from "react";
import Card from "./Card";
import Pagination from "../Fragments/Pagination";

const data = [
  {
    title: "Dynamic Accountability Architect",
    company: "Herman - Jerde",
    location: "Pacochashire",
    salary: "888.59",
    sub_classification: "Web",
    classification: "Manager",
    listing_date: "2061-02-10T11:16:55.020Z",
    id: "1",
  },
  {
    title: "Internal Paradigm Supervisor",
    company: "Von and Sons",
    location: "Haneboro",
    salary: "136.38",
    sub_classification: "Accountability",
    classification: "Administrator",
    listing_date: "2048-06-29T13:22:07.893Z",
    id: "2",
  },
  {
    title: "Global Division Supervisor",
    company: "Heidenreich Inc",
    location: "Lake Joy",
    salary: "741.21",
    sub_classification: "Factors",
    classification: "Orchestrator",
    listing_date: "2006-06-08T16:07:37.677Z",
    id: "3",
  },
  {
    title: "Lead Group Developer",
    company: "Krajcik Inc",
    location: "Kielfurt",
    salary: "104.73",
    sub_classification: "Integration",
    classification: "Associate",
    listing_date: "2050-08-24T08:48:11.184Z",
    id: "4",
  },
  {
    title: "Legacy Infrastructure Manager",
    company: "Haag - Ernser",
    location: "Anaheim",
    salary: "841.80",
    sub_classification: "Division",
    classification: "Engineer",
    listing_date: "1997-09-22T12:00:45.948Z",
    id: "5",
  },
  {
    title: "Forward Implementation Planner",
    company: "Bernhard and Sons",
    location: "Port Kristopherstead",
    salary: "143.37",
    sub_classification: "Identity",
    classification: "Director",
    listing_date: "2000-01-13T11:49:24.538Z",
    id: "6",
  },
  {
    title: "Chief Factors Agent",
    company: "Pfannerstill - Hilll",
    location: "Port Julien",
    salary: "69.80",
    sub_classification: "Tactics",
    classification: "Technician",
    listing_date: "2076-01-01T11:09:23.540Z",
    id: "7",
  },
  {
    title: "Senior Web Officer",
    company: "Aufderhar, Daniel and Wilderman",
    location: "Henderson",
    salary: "935.05",
    sub_classification: "Program",
    classification: "Analyst",
    listing_date: "2012-04-19T13:56:18.926Z",
    id: "8",
  },
  {
    title: "National Operations Planner",
    company: "Balistreri Inc",
    location: "Adellaboro",
    salary: "41.97",
    sub_classification: "Division",
    classification: "Orchestrator",
    listing_date: "1992-11-17T07:48:37.103Z",
    id: "9",
  },
  {
    title: "Future Infrastructure Coordinator",
    company: "Konopelski Group",
    location: "Erynchester",
    salary: "618.37",
    sub_classification: "Optimization",
    classification: "Agent",
    listing_date: "2079-07-18T11:53:48.725Z",
    id: "10",
  },
  {
    title: "Dynamic Infrastructure Administrator",
    company: "Hauck Group",
    location: "Waltham",
    salary: "843.87",
    sub_classification: "Research",
    classification: "Agent",
    listing_date: "2070-12-25T12:01:13.164Z",
    id: "11",
  },
  {
    title: "National Metrics Consultant",
    company: "Stiedemann, Rolfson and Witting",
    location: "East Lyda",
    salary: "535.51",
    sub_classification: "Operations",
    classification: "Manager",
    listing_date: "2037-04-17T19:10:30.582Z",
    id: "12",
  },
  {
    title: "National Response Executive",
    company: "Fadel, Larkin and Powlowski",
    location: "Howefort",
    salary: "48.12",
    sub_classification: "Optimization",
    classification: "Director",
    listing_date: "2049-05-04T22:42:35.840Z",
    id: "13",
  },
  {
    title: "Dynamic Functionality Representative",
    company: "Mann - Leannon",
    location: "Port Jeanton",
    salary: "816.35",
    sub_classification: "Applications",
    classification: "Administrator",
    listing_date: "1991-10-21T17:54:17.184Z",
    id: "14",
  },
  {
    title: "Human Mobility Manager",
    company: "Beer - Ratke",
    location: "Temecula",
    salary: "131.74",
    sub_classification: "Marketing",
    classification: "Strategist",
    listing_date: "2052-03-22T06:18:32.288Z",
    id: "15",
  },
  {
    title: "Internal Functionality Executive",
    company: "Turcotte - Lehner",
    location: "Noahtown",
    salary: "408.65",
    sub_classification: "Creative",
    classification: "Associate",
    listing_date: "2049-12-26T17:35:37.900Z",
    id: "16",
  },
  {
    title: "Dynamic Response Officer",
    company: "Batz - Metz",
    location: "Lake Regan",
    salary: "564.75",
    sub_classification: "Assurance",
    classification: "Assistant",
    listing_date: "2050-01-02T17:27:36.188Z",
    id: "17",
  },
  {
    title: "Investor Data Engineer",
    company: "Yost Group",
    location: "Dietrichhaven",
    salary: "287.60",
    sub_classification: "Division",
    classification: "Administrator",
    listing_date: "2093-05-09T17:09:05.562Z",
    id: "18",
  },
  {
    title: "Corporate Group Developer",
    company: "Hamill - McKenzie",
    location: "Lewisfurt",
    salary: "731.78",
    sub_classification: "Communications",
    classification: "Strategist",
    listing_date: "2080-08-28T07:49:45.377Z",
    id: "19",
  },
  {
    title: "Future Division Producer",
    company: "Weimann - Gusikowski",
    location: "West Karsonside",
    salary: "210.33",
    sub_classification: "Accountability",
    classification: "Technician",
    listing_date: "2047-03-24T00:14:01.217Z",
    id: "20",
  },
  {
    title: "Customer Security Specialist",
    company: "Bradtke, Cormier and Crooks",
    location: "Klingworth",
    salary: "644.65",
    sub_classification: "Branding",
    classification: "Analyst",
    listing_date: "2080-12-15T23:59:57.027Z",
    id: "21",
  },
  {
    title: "Internal Web Analyst",
    company: "Ledner Group",
    location: "New Rochelle",
    salary: "49.51",
    sub_classification: "Operations",
    classification: "Assistant",
    listing_date: "1995-02-28T08:18:34.069Z",
    id: "22",
  },
  {
    title: "Forward Marketing Supervisor",
    company: "Simonis - Nitzsche",
    location: "Shanashire",
    salary: "7.21",
    sub_classification: "Group",
    classification: "Engineer",
    listing_date: "2085-07-31T16:43:51.908Z",
    id: "23",
  },
  {
    title: "Future Program Architect",
    company: "Reilly, Yost and Bradtke",
    location: "Indianapolis",
    salary: "8.06",
    sub_classification: "Branding",
    classification: "Architect",
    listing_date: "2015-11-08T11:42:10.643Z",
    id: "24",
  },
  {
    title: "Customer Division Agent",
    company: "Glover, Rippin and Johnston",
    location: "Coltenland",
    salary: "208.79",
    sub_classification: "Assurance",
    classification: "Engineer",
    listing_date: "2001-03-16T08:06:00.163Z",
    id: "25",
  },
  {
    title: "National Creative Assistant",
    company: "Walter LLC",
    location: "Westminster",
    salary: "111.90",
    sub_classification: "Division",
    classification: "Architect",
    listing_date: "2082-07-20T18:06:24.160Z",
    id: "26",
  },
  {
    title: "Chief Branding Administrator",
    company: "Parker Inc",
    location: "Alfonsomouth",
    salary: "891.39",
    sub_classification: "Usability",
    classification: "Supervisor",
    listing_date: "2027-12-10T15:09:30.459Z",
    id: "27",
  },
  {
    title: "Legacy Factors Executive",
    company: "Schulist, Jakubowski and Emard",
    location: "Gutmannberg",
    salary: "244.96",
    sub_classification: "Web",
    classification: "Director",
    listing_date: "2077-12-26T12:07:35.870Z",
    id: "28",
  },
  {
    title: "Central Security Director",
    company: "Prosacco Group",
    location: "Yundtfurt",
    salary: "669.68",
    sub_classification: "Branding",
    classification: "Representative",
    listing_date: "2014-02-02T13:36:04.392Z",
    id: "29",
  },
  {
    title: "Corporate Configuration Director",
    company: "West LLC",
    location: "Port Mallory",
    salary: "796.08",
    sub_classification: "Security",
    classification: "Agent",
    listing_date: "2062-10-12T19:02:48.876Z",
    id: "30",
  },
  {
    title: "Regional Web Architect",
    company: "Beer, Hudson and Toy",
    location: "East Traceytown",
    salary: "465.71",
    sub_classification: "Paradigm",
    classification: "Technician",
    listing_date: "2065-06-21T03:07:16.445Z",
    id: "31",
  },
  {
    title: "Investor Quality Strategist",
    company: "Bode LLC",
    location: "North Ulicesborough",
    salary: "845.51",
    sub_classification: "Accounts",
    classification: "Orchestrator",
    listing_date: "1993-01-19T20:41:35.282Z",
    id: "32",
  },
  {
    title: "Central Quality Director",
    company: "Auer - Abshire",
    location: "Twilastead",
    salary: "588.31",
    sub_classification: "Optimization",
    classification: "Consultant",
    listing_date: "2048-06-22T07:26:39.698Z",
    id: "33",
  },
  {
    title: "Chief Implementation Specialist",
    company: "Torp - Corwin",
    location: "Caguas",
    salary: "19.96",
    sub_classification: "Implementation",
    classification: "Agent",
    listing_date: "2039-11-25T19:49:06.237Z",
    id: "34",
  },
  {
    title: "Dynamic Configuration Representative",
    company: "Paucek - Borer",
    location: "San Jose",
    salary: "677.96",
    sub_classification: "Usability",
    classification: "Strategist",
    listing_date: "2088-09-27T06:31:23.497Z",
    id: "35",
  },
  {
    title: "Senior Integration Manager",
    company: "Hauck LLC",
    location: "South Giles",
    salary: "541.69",
    sub_classification: "Research",
    classification: "Representative",
    listing_date: "2089-06-21T23:20:11.609Z",
    id: "36",
  },
  {
    title: "Chief Integration Associate",
    company: "Homenick, Mitchell and Sauer",
    location: "Gradyfield",
    salary: "524.10",
    sub_classification: "Security",
    classification: "Designer",
    listing_date: "2072-07-15T21:57:16.832Z",
    id: "37",
  },
  {
    title: "National Marketing Assistant",
    company: "Mitchell, Bergnaum and Kihn",
    location: "Utica",
    salary: "878.54",
    sub_classification: "Infrastructure",
    classification: "Coordinator",
    listing_date: "2087-03-20T05:33:54.544Z",
    id: "38",
  },
  {
    title: "Chief Quality Facilitator",
    company: "Kemmer, Kautzer and Orn",
    location: "East Maude",
    salary: "207.93",
    sub_classification: "Optimization",
    classification: "Planner",
    listing_date: "2021-07-27T09:00:14.656Z",
    id: "39",
  },
  {
    title: "Investor Functionality Developer",
    company: "Bradtke - Wilkinson",
    location: "West Zoiemouth",
    salary: "398.58",
    sub_classification: "Branding",
    classification: "Consultant",
    listing_date: "2063-01-29T21:29:53.230Z",
    id: "40",
  },
  {
    title: "Central Accountability Director",
    company: "Quigley - Farrell",
    location: "Spring Hill",
    salary: "262.32",
    sub_classification: "Solutions",
    classification: "Engineer",
    listing_date: "2032-02-03T16:33:41.395Z",
    id: "41",
  },
  {
    title: "Customer Accounts Architect",
    company: "Hansen, Heller and Zieme",
    location: "Meridian",
    salary: "773.14",
    sub_classification: "Markets",
    classification: "Assistant",
    listing_date: "2089-11-30T17:24:50.303Z",
    id: "42",
  },
  {
    title: "District Program Analyst",
    company: "Hand - Collier",
    location: "South Aurelia",
    salary: "772.99",
    sub_classification: "Interactions",
    classification: "Agent",
    listing_date: "2010-12-04T08:18:40.571Z",
    id: "43",
  },
  {
    title: "Dynamic Functionality Planner",
    company: "Miller, Kling and Smitham",
    location: "Norman",
    salary: "162.42",
    sub_classification: "Identity",
    classification: "Supervisor",
    listing_date: "2054-04-22T06:58:51.932Z",
    id: "44",
  },
  {
    title: "Future Marketing Agent",
    company: "Kemmer, Moore and Heathcote",
    location: "Napa",
    salary: "948.68",
    sub_classification: "Applications",
    classification: "Developer",
    listing_date: "2002-01-10T23:45:28.528Z",
    id: "45",
  },
  {
    title: "Legacy Web Specialist",
    company: "Dare, Ullrich and Adams",
    location: "Maggioshire",
    salary: "843.76",
    sub_classification: "Brand",
    classification: "Administrator",
    listing_date: "2048-02-15T16:06:20.582Z",
    id: "46",
  },
  {
    title: "Future Accountability Analyst",
    company: "Larson - Orn",
    location: "South Jordan",
    salary: "44.85",
    sub_classification: "Usability",
    classification: "Officer",
    listing_date: "1992-09-19T10:27:28.113Z",
    id: "47",
  },
  {
    title: "Product Response Director",
    company: "Langworth Group",
    location: "Port Jerad",
    salary: "999.42",
    sub_classification: "Usability",
    classification: "Supervisor",
    listing_date: "2046-03-25T08:36:04.282Z",
    id: "48",
  },
  {
    title: "Investor Communications Engineer",
    company: "Haag Inc",
    location: "Fort Rosa",
    salary: "214.86",
    sub_classification: "Assurance",
    classification: "Orchestrator",
    listing_date: "2095-01-08T04:49:46.059Z",
    id: "49",
  },
  {
    title: "Global Assurance Orchestrator",
    company: "Hermann Group",
    location: "West Hermina",
    salary: "222.30",
    sub_classification: "Usability",
    classification: "Representative",
    listing_date: "2004-08-22T07:31:54.738Z",
    id: "50",
  },
  {
    title: "Direct Accounts Representative",
    company: "Orn, Murray and Treutel",
    location: "East Goldaport",
    salary: "41.15",
    sub_classification: "Factors",
    classification: "Officer",
    listing_date: "2017-06-02T04:59:19.232Z",
    id: "51",
  },
  {
    title: "Direct Quality Producer",
    company: "Towne and Sons",
    location: "Lake Lorenzworth",
    salary: "971.55",
    sub_classification: "Optimization",
    classification: "Orchestrator",
    listing_date: "2031-06-02T07:51:36.783Z",
    id: "52",
  },
  {
    title: "Corporate Tactics Analyst",
    company: "Jaskolski - Haag",
    location: "Christiansenchester",
    salary: "907.33",
    sub_classification: "Division",
    classification: "Officer",
    listing_date: "2003-01-18T21:22:12.246Z",
    id: "53",
  },
  {
    title: "Direct Assurance Technician",
    company: "Wiegand - Runolfsson",
    location: "Hirthebury",
    salary: "122.89",
    sub_classification: "Quality",
    classification: "Developer",
    listing_date: "2057-11-28T17:37:50.328Z",
    id: "54",
  },
  {
    title: "Regional Marketing Producer",
    company: "Koepp LLC",
    location: "Hermistonchester",
    salary: "64.42",
    sub_classification: "Research",
    classification: "Administrator",
    listing_date: "2094-04-25T13:34:54.134Z",
    id: "55",
  },
  {
    title: "International Intranet Agent",
    company: "Jacobi, Donnelly and Altenwerth",
    location: "DuBuqueville",
    salary: "524.67",
    sub_classification: "Data",
    classification: "Strategist",
    listing_date: "2006-01-05T18:54:01.098Z",
    id: "56",
  },
  {
    title: "Internal Infrastructure Analyst",
    company: "Sporer, Gleichner and Waters",
    location: "Brandoport",
    salary: "159.47",
    sub_classification: "Intranet",
    classification: "Orchestrator",
    listing_date: "2010-04-17T15:33:19.075Z",
    id: "57",
  },
  {
    title: "Lead Configuration Technician",
    company: "Hintz Group",
    location: "Lake Damienview",
    salary: "667.61",
    sub_classification: "Paradigm",
    classification: "Associate",
    listing_date: "2029-10-19T14:39:35.926Z",
    id: "58",
  },
  {
    title: "Dynamic Markets Technician",
    company: "Langosh, Lehner and Watsica",
    location: "South Damienfort",
    salary: "535.51",
    sub_classification: "Markets",
    classification: "Agent",
    listing_date: "2011-04-24T00:40:11.541Z",
    id: "59",
  },
  {
    title: "Lead Operations Assistant",
    company: "Fadel LLC",
    location: "East Freeman",
    salary: "421.48",
    sub_classification: "Metrics",
    classification: "Associate",
    listing_date: "2087-07-15T22:53:47.005Z",
    id: "60",
  },
  {
    title: "International Accounts Analyst",
    company: "Pollich Group",
    location: "Robertaland",
    salary: "579.93",
    sub_classification: "Marketing",
    classification: "Administrator",
    listing_date: "2014-10-13T13:20:18.251Z",
    id: "61",
  },
  {
    title: "District Configuration Orchestrator",
    company: "Macejkovic Group",
    location: "Coleton",
    salary: "941.91",
    sub_classification: "Markets",
    classification: "Representative",
    listing_date: "2053-03-15T08:47:59.647Z",
    id: "62",
  },
  {
    title: "Regional Markets Technician",
    company: "Purdy - Padberg",
    location: "Rigobertofort",
    salary: "996.06",
    sub_classification: "Functionality",
    classification: "Engineer",
    listing_date: "2077-05-11T14:42:45.121Z",
    id: "63",
  },
  {
    title: "Direct Web Engineer",
    company: "Leffler, Donnelly and O'Kon",
    location: "North Sadieville",
    salary: "893.91",
    sub_classification: "Integration",
    classification: "Executive",
    listing_date: "2045-10-20T07:42:30.458Z",
    id: "64",
  },
  {
    title: "Lead Paradigm Strategist",
    company: "Sporer - Kuphal",
    location: "New Deven",
    salary: "645.31",
    sub_classification: "Assurance",
    classification: "Planner",
    listing_date: "2036-10-03T04:21:53.210Z",
    id: "65",
  },
  {
    title: "Senior Research Architect",
    company: "Nienow - Bernier",
    location: "Arvelberg",
    salary: "773.58",
    sub_classification: "Data",
    classification: "Designer",
    listing_date: "2006-01-20T10:03:22.616Z",
    id: "66",
  },
  {
    title: "Global Interactions Representative",
    company: "O'Conner - MacGyver",
    location: "North Paula",
    salary: "756.32",
    sub_classification: "Web",
    classification: "Executive",
    listing_date: "2059-12-17T02:22:55.410Z",
    id: "67",
  },
  {
    title: "Customer Interactions Assistant",
    company: "Yost Inc",
    location: "Knoxville",
    salary: "452.85",
    sub_classification: "Accounts",
    classification: "Developer",
    listing_date: "2009-12-23T21:10:22.969Z",
    id: "68",
  },
  {
    title: "National Paradigm Representative",
    company: "Goodwin - Stanton",
    location: "North Kittymouth",
    salary: "450.90",
    sub_classification: "Factors",
    classification: "Engineer",
    listing_date: "1998-11-23T02:35:07.159Z",
    id: "69",
  },
  {
    title: "Senior Communications Orchestrator",
    company: "White and Sons",
    location: "Felicitaview",
    salary: "644.87",
    sub_classification: "Operations",
    classification: "Manager",
    listing_date: "2031-01-26T22:00:41.035Z",
    id: "70",
  },
  {
    title: "Investor Creative Consultant",
    company: "Braun and Sons",
    location: "Guiseppefurt",
    salary: "720.81",
    sub_classification: "Metrics",
    classification: "Representative",
    listing_date: "2076-02-04T08:55:12.081Z",
    id: "71",
  },
  {
    title: "Chief Quality Analyst",
    company: "Beatty - Wolf",
    location: "Leraton",
    salary: "675.34",
    sub_classification: "Brand",
    classification: "Designer",
    listing_date: "2015-02-18T09:53:04.916Z",
    id: "72",
  },
  {
    title: "Corporate Intranet Developer",
    company: "Streich - Robel",
    location: "Laurelfield",
    salary: "420.47",
    sub_classification: "Optimization",
    classification: "Officer",
    listing_date: "2041-04-18T10:12:40.853Z",
    id: "73",
  },
  {
    title: "Human Brand Associate",
    company: "Kiehn - Gutmann",
    location: "Borertown",
    salary: "235.17",
    sub_classification: "Usability",
    classification: "Officer",
    listing_date: "2032-04-15T18:21:38.959Z",
    id: "74",
  },
  {
    title: "Legacy Directives Manager",
    company: "Huel LLC",
    location: "Russelstead",
    salary: "506.56",
    sub_classification: "Brand",
    classification: "Developer",
    listing_date: "2078-09-01T01:06:21.751Z",
    id: "75",
  },
  {
    title: "Dynamic Brand Coordinator",
    company: "Osinski, Blick and Wuckert",
    location: "Oak Park",
    salary: "893.73",
    sub_classification: "Interactions",
    classification: "Developer",
    listing_date: "2003-11-23T17:57:57.354Z",
    id: "76",
  },
  {
    title: "Central Usability Liaison",
    company: "Dickinson - Johnston",
    location: "East Kirkhaven",
    salary: "364.73",
    sub_classification: "Accounts",
    classification: "Officer",
    listing_date: "2041-02-12T13:48:39.432Z",
    id: "77",
  },
  {
    title: "Direct Directives Analyst",
    company: "Blick, Howell and Aufderhar",
    location: "Darronhaven",
    salary: "179.80",
    sub_classification: "Intranet",
    classification: "Coordinator",
    listing_date: "1994-06-17T08:47:19.688Z",
    id: "78",
  },
  {
    title: "Senior Brand Technician",
    company: "Lebsack, Strosin and Ankunding",
    location: "West Sacramento",
    salary: "821.51",
    sub_classification: "Operations",
    classification: "Officer",
    listing_date: "2082-04-21T03:59:10.174Z",
    id: "79",
  },
  {
    title: "International Directives Technician",
    company: "Rohan LLC",
    location: "Fort Marian",
    salary: "431.98",
    sub_classification: "Optimization",
    classification: "Planner",
    listing_date: "2060-12-22T21:01:19.985Z",
    id: "80",
  },
  {
    title: "Investor Mobility Orchestrator",
    company: "Reichel Inc",
    location: "Legroshaven",
    salary: "252.32",
    sub_classification: "Infrastructure",
    classification: "Analyst",
    listing_date: "1994-04-22T09:18:27.582Z",
    id: "81",
  },
  {
    title: "Customer Accountability Manager",
    company: "Haley, Welch and Konopelski",
    location: "Ilianaberg",
    salary: "166.99",
    sub_classification: "Data",
    classification: "Officer",
    listing_date: "2089-10-26T08:35:28.799Z",
    id: "82",
  },
  {
    title: "Investor Web Administrator",
    company: "Bruen Group",
    location: "Bloomington",
    salary: "243.09",
    sub_classification: "Group",
    classification: "Technician",
    listing_date: "2055-04-24T17:58:26.463Z",
    id: "83",
  },
  {
    title: "District Security Manager",
    company: "Rempel - Schroeder",
    location: "Cormiercester",
    salary: "606.27",
    sub_classification: "Interactions",
    classification: "Strategist",
    listing_date: "2051-02-16T07:32:26.148Z",
    id: "84",
  },
  {
    title: "Investor Assurance Architect",
    company: "Muller, White and Casper",
    location: "Menifee",
    salary: "854.27",
    sub_classification: "Implementation",
    classification: "Officer",
    listing_date: "2000-10-18T06:53:36.432Z",
    id: "85",
  },
  {
    title: "District Infrastructure Executive",
    company: "Olson - Kilback",
    location: "East Jaredhaven",
    salary: "837.89",
    sub_classification: "Group",
    classification: "Supervisor",
    listing_date: "2001-07-15T02:04:58.545Z",
    id: "86",
  },
  {
    title: "Direct Group Planner",
    company: "Beahan - Reynolds",
    location: "West Glenda",
    salary: "174.05",
    sub_classification: "Accounts",
    classification: "Analyst",
    listing_date: "2002-11-15T20:46:43.603Z",
    id: "87",
  },
  {
    title: "Chief Division Engineer",
    company: "Gleichner - Towne",
    location: "Cathedral City",
    salary: "490.43",
    sub_classification: "Accounts",
    classification: "Director",
    listing_date: "2093-09-01T20:22:30.310Z",
    id: "88",
  },
  {
    title: "International Web Architect",
    company: "Corwin Inc",
    location: "North Kassandrabury",
    salary: "528.85",
    sub_classification: "Security",
    classification: "Manager",
    listing_date: "2085-05-30T14:51:12.720Z",
    id: "89",
  },
  {
    title: "Direct Implementation Associate",
    company: "Ebert, Schmidt and Purdy",
    location: "New Elsie",
    salary: "776.39",
    sub_classification: "Creative",
    classification: "Liaison",
    listing_date: "2099-12-09T17:09:06.915Z",
    id: "90",
  },
  {
    title: "Product Usability Executive",
    company: "Strosin - Dickens",
    location: "West Consuelobury",
    salary: "366.29",
    sub_classification: "Functionality",
    classification: "Administrator",
    listing_date: "2015-01-18T03:33:21.496Z",
    id: "91",
  },
  {
    title: "Principal Metrics Representative",
    company: "Kemmer, Witting and Schroeder",
    location: "Olsonfort",
    salary: "140.00",
    sub_classification: "Response",
    classification: "Director",
    listing_date: "2081-05-01T08:00:37.913Z",
    id: "92",
  },
  {
    title: "Chief Paradigm Developer",
    company: "Wyman, Miller and Predovic",
    location: "Hodkiewiczfort",
    salary: "683.04",
    sub_classification: "Quality",
    classification: "Administrator",
    listing_date: "2014-03-06T10:52:05.376Z",
    id: "93",
  },
  {
    title: "Future Functionality Orchestrator",
    company: "Toy, Runolfsdottir and Wisoky",
    location: "North Dimitrihaven",
    salary: "307.57",
    sub_classification: "Usability",
    classification: "Manager",
    listing_date: "2069-07-20T19:44:56.857Z",
    id: "94",
  },
  {
    title: "Regional Identity Liaison",
    company: "Jakubowski - Abbott",
    location: "Danielchester",
    salary: "915.19",
    sub_classification: "Branding",
    classification: "Strategist",
    listing_date: "2037-01-18T06:18:47.378Z",
    id: "95",
  },
  {
    title: "Senior Branding Representative",
    company: "Kuphal, Mraz and Kshlerin",
    location: "Vallejo",
    salary: "831.74",
    sub_classification: "Metrics",
    classification: "Developer",
    listing_date: "1997-05-17T19:37:40.510Z",
    id: "96",
  },
  {
    title: "Principal Accounts Specialist",
    company: "Goodwin, Schaden and Collins",
    location: "O'Konstead",
    salary: "175.98",
    sub_classification: "Directives",
    classification: "Director",
    listing_date: "2007-03-20T23:42:32.771Z",
    id: "97",
  },
  {
    title: "Senior Assurance Analyst",
    company: "Ritchie - Parker",
    location: "West Perry",
    salary: "426.82",
    sub_classification: "Program",
    classification: "Assistant",
    listing_date: "2014-02-05T03:45:36.379Z",
    id: "98",
  },
  {
    title: "Customer Communications Analyst",
    company: "Jakubowski and Sons",
    location: "South Newton",
    salary: "891.89",
    sub_classification: "Integration",
    classification: "Orchestrator",
    listing_date: "2053-08-02T01:32:36.837Z",
    id: "99",
  },
  {
    title: "Legacy Tactics Supervisor",
    company: "Tromp Inc",
    location: "Streichborough",
    salary: "908.18",
    sub_classification: "Data",
    classification: "Architect",
    listing_date: "2069-12-05T09:51:23.315Z",
    id: "100",
    bullet_points: "Nongkrong; Makan",
  },
];

const DashboardLayout = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [jobsPerPage, setJobsPerPage] = useState(10);

  const totalData = data.length;
  const indexOfLastJob = currentPage * jobsPerPage;
  const indexOfFirstJob = indexOfLastJob - jobsPerPage;
  const currentJobs = data.slice(indexOfFirstJob, indexOfLastJob);

  const paginateFront = () => setCurrentPage(currentPage + 1);
  const paginateBack = () => setCurrentPage(currentPage - 1);
  const paginate = (pageNumber) => setCurrentPage(pageNumber);
  const startIndex = currentPage * jobsPerPage - jobsPerPage + 1;
  const endIndex = Math.min(currentPage * jobsPerPage, totalData);

  const handlePage = (page) => {
    setJobsPerPage(page);
  };

  return (
    <div className="p-8 gap-8 flex flex-col flex-1">
      <div>
        <p className="text-slate-900">
          Showing <span className="font-medium">{startIndex}</span> to{" "}
          <span className="font-medium">{endIndex}</span> of{" "}
          <span className="font-medium">{totalData}</span> results
        </p>
      </div>
      <div className="flex-1">
        <div className="grid grid-cols-4 gap-4">
          {currentJobs?.map((dt) => {
            return <Card key={dt.id} data={dt} />;
          })}
        </div>
      </div>
      <Pagination
        jobsPerPage={jobsPerPage}
        handlePage={handlePage}
        totalData={totalData}
        paginateFront={paginateFront}
        paginateBack={paginateBack}
        currentPage={currentPage}
        paginate={paginate}
        endIndex={endIndex}
      />
    </div>
  );
};

export default DashboardLayout;
